### ISSUE TITLE
Add search results highlighting like fzf

### ISSUE THREAD

**Issue by korniychuk** [ddworken/hishtory#112]
The `hishtory` is excellent! I would be happy to switch from `fzf` to it to synchronize the history on all my devices.
I see you actively developing the tool! It's great!

However, underlining is sorely lacking.
For example, how it looks like in `fzf`.
<img width="599" alt="Screenshot 2023-09-23 at 13 50 04@2x" src="https://github.com/ddworken/hishtory/assets/11693557/e75ac2a2-546f-45d3-b947-1156227f27eb">

**Comment by ddworken** [comment]
Thanks for the FR! To confirm, your suggestion is that for each command we somehow highlight the text in the command that is matching the query?

**Comment by ddworken** [comment]
Just FYI, I've started to work on this and have a current prototype where matches are bolded:

<img width="1118" alt="Screenshot 2023-09-26 at 8 55 05 PM" src="https://github.com/ddworken/hishtory/assets/5304541/4a472434-c01c-4e21-8c71-f256c0488d9d">

I'll get this released relatively soon :)

**Comment by ddworken** [comment]
If you run `hishtory update` to get the latest version of hishtory, and opt-in to beta features via `hishtory config-set beta-mode true`, you can try this out! I'd love any feedback you have on this feature.

**Comment by ddworken** [comment]
This is now fully released and enabled by default! Please let me know if you have any feedback/thoughts on this.
