### ISSUE TITLE
presaveHistoryEntry fish

### ISSUE THREAD

**Issue by fawqsir** [ddworken/hishtory#117]
I should have raised a ticket (issue) a few weeks ago... Whenever I try to exit an arch based fish shell I get this error (PID# is all that changes): 

```
❯ exit

There are still jobs active:

PID  Command
9591  hishtory presaveHistoryEntry fish "$_hishtory_command" $_hishtory_start_time &

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.
```
I then need to type exit again and the terminal will close. Happens when I ssh into a remote server and than try to run exit as well. All systems are working well over https through a reverse proxy, as I can search and most recent activity is shown.

hiSHtory: v0.237

**Comment by ddworken** [comment]
Thank you for the detailed

**Comment by ddworken** [comment]
Thanks again for filing this! If you run `hishtory update` you'll get the latest version that fixes this bug (though note that you will have to restart your terminal).
