### ISSUE TITLE
`database is locked (261)` error

### ISSUE THREAD

**Issue by haberdashPI** [ddworken/hishtory#119]
```
 8:11am ❯ hishtory init $MY_SECRET_KEY
2023/10/29 08:11:15 hishtory v0.242 fatal error at github.com/ddworken/hishtory/client/cmd/install.go:68: database is locked (261)
```

**Comment by ddworken** [comment]
Thanks for filing the issue! I believe this is a flaky issue, so if you retry I believe it should work. If not, 4352f61 should fix this (though I'll wait to release it until tests finish running).

**Comment by ddworken** [comment]
Ok, this should be fixed now and I haven't been able to reproduce this issue with the latest released version, so I'm closing this. If you still are experiencing any issues please let me know!
