### ISSUE TITLE
Customize colorscheme

### ISSUE THREAD

**Issue by zhou13** [ddworken/hishtory#134]
The default color is somewhat low-contrast with my current terminal colorscheme. It seems that the color is hard-coded. I wish I could invert the foreground color of the selected column.
<img width="960" alt="Screenshot 2023-11-28 at 10 48 30 AM" src="https://github.com/ddworken/hishtory/assets/576382/8ee9660e-4545-44ec-b680-3c4b2db85f01">

**Comment by ddworken** [comment]
Ok, this is now supported! If you run `hishtory update` you'll get the latest version which includes support for configuring a custom color scheme. Check out `hishtory config-get color-scheme` for information on the current default color scheme, and `hishtory config-set color-scheme` for information on how to customize it. Please let me know what you think and if you have any other suggestions!

**Comment by zhou13** [comment]
@ddworken Thank you for the work! I just tested this new feature and it seems that it is likely of buggy.  Oh my computer, I got
```
$ hishtory config-get color-scheme
selected-text: #ffff99
selected-background: #3300ff
border-color: #585858
```
Unforunately, the hex code is wrong: my background color is `#caa9fa`. Since I set the color in my terminal, I don't think hishtory can get access to the hex value.

Now I execute `hishtory config-set color-scheme selected-background "#663399"`, the background color is simply gone:
![image](https://github.com/ddworken/hishtory/assets/576382/5c50aa23-d8ef-4401-aafa-2ae17bd13030)

It appears that #663399 is not a valid color. Set it back to #3300ff restore the original background color.

**Comment by ddworken** [comment]
Ah, thank you for this feedback! You are entirely right that this isn't working quite yet, see [30f94c1](https://github.com/ddworken/hishtory/commit/30f94c1c78ddb076074712812b566d7a72946330) for the details. I'll get that change officially released in the next couple days, but if you'd like to give it a shot--feel free to clone this repo and then `go build; ./hishtory install` to install it ahead of time. I'll let you know once this has been released!

**Comment by ddworken** [comment]
If you run `hishtory update`, you'll get the latest version with [30f94c1](https://github.com/ddworken/hishtory/commit/30f94c1c78ddb076074712812b566d7a72946330) included. Please let me know if this works for you!

**Comment by zhou13** [comment]
After updating to the newest version, I got
![image](https://github.com/ddworken/hishtory/assets/576382/868bbfe5-ea6a-4cde-886d-474f7cf56c63)

It looks nice but I don't think the hex value color of bg is quite right. `#663399` should be purple like as shown below:
![image](https://github.com/ddworken/hishtory/assets/576382/128b67ff-1b78-456f-877f-1b86645e635f)

**Comment by ddworken** [comment]
Yup, as described in the comment added in [30f94c1](https://github.com/ddworken/hishtory/commit/30f94c1c78ddb076074712812b566d7a72946330), it is currently approximating it with 256 colors. [77313df](https://github.com/ddworken/hishtory/commit/77313dfb48b1585996d9e095d092c80bb9ded209) will add support for full terminal "TrueColor" support. Feel free to clone and build yourself if you want to try this out early, otherwise I'll let you know once it has been released. :)

**Comment by ddworken** [comment]
`hishtory update` will give you the latest version, LMK if you notice any other issues! :)

**Comment by ddworken** [comment]
Thanks again for all the feedback and help with this! I'm going to go ahead and mark this as closed, but please let me know if you run into any other issues!
