### ISSUE TITLE
Warp Terminal support

### ISSUE THREAD

**Issue by cowboygneox** [ddworken/hishtory#141]
I'm not sure if this is a bug or a feature request, I mostly just want to understand how it works.

I've been trying out [Warp](https://www.warp.dev). It has its own Ctrl-R integration, fine, but what's weird is that Hishtory can read Warp's command history, but Warp cannot read Hishtory's commands created in a different terminal like iTerm. I'm not sure how Hishtory binds itself to the zsh history, but apparently Warp doesn't work with it.

Any thoughts on how I can debug this, or if this is expected behavior?

**Comment by ddworken** [comment]
I'm marking this as closed, but if you still are running into issues here that you think could be improved upon by hishtory, please reopen this!
