### ISSUE TITLE
Frontend to query the encrypted data

### ISSUE THREAD

**Issue by bloodyburger** [ddworken/hishtory#147]
I just installed today on multiple servers and already liking it. I am using existing Postgresql as the backend and wondering if there can be a frontend like a simple UI where we can search the history.

**Comment by ddworken** [comment]
Thanks for the issue! Can you explain more in terms of what type of frontend you're envisioning here? Are you picturing a web frontend? Generally, I see the hishtory CLI as the frontend for the encrypted data, though I can see the potential utility of supporting some sort of web frontend for viewing/querying your history.

**Comment by ddworken** [comment]
I'm closing this out since there's no reply, but if you do see this, please re-open this so I can take another look!

**Comment by bloodyburger** [comment]
Yes a web frontend with simple search would work, may be in the future can support APIs as well.
