### ISSUE TITLE
hishtory init erases current history

### ISSUE THREAD

**Issue by tavdog** [ddworken/hishtory#15]
Is there a way to sync two already existing history files ?  I have lot of history on two computers, want to sync but don't want to lose all the history from one of them.

**Comment by ddworken** [comment]
I'm assuming that you mean you have pre-existing history that you want to include? This is a good point, and something I can push out an update to do better with. 

But as a workaround, you can:

1. Install hishtory on computer 1
2. Install hishtory on computer 2
3. Run hishtory init on computer 2 to set the shared key and confirm that this will delete the local hishtory DB (it won't affect your local bash/zsh/fish history)
4. Run `echo '' | hishtory import` on computer 2 to re-import from your local pre-existing history

**Comment by tavdog** [comment]
thanks.  but how does echo '' do anything ?

**Comment by ddworken** [comment]
Fixed :) 

Now running `hishtory init` will clear the local history DB, and then re-import all ones from the shell history files.
