### ISSUE TITLE
install fails in shared hosting environment (dreamhost vps)

### ISSUE THREAD

**Issue by tavdog** [ddworken/hishtory#16]
sh: /tmp/hishtory-client: Permission denied
Traceback (most recent call last):
  File "<stdin>", line 36, in <module>
Exception: failed to install downloaded hishtory client via `/tmp/hishtory-client install`!

**Comment by tavdog** [comment]
Fixed by hardcoding /home/USERNAME/tmp  in install.py

**Comment by ddworken** [comment]
Ah nice! This is a good point about /tmp/ not always being a writable directory. I'll work on an update to have it look for other writable directories if /tmp/ doesn't work.

**Comment by tavdog** [comment]
It seemed the hishtory-client was indeed in the /tmp directory but I don't think /tmp allows execution on my system.

**Comment by ddworken** [comment]
Ah, that makes sense. I added a new environment variable (`TMPDIR`) that can be used to override the tmp dir to an alternative path that isn't mounted `noexec`. For anyone else who comes across this, I recommend something like `mkdir ~/.hishtory/; export TMPDIR=$HOME/.hishtory/`.
