### ISSUE TITLE
Newlines in command break second invocation

### ISSUE THREAD

**Issue by bnichs** [ddworken/hishtory#163]
```
% hishtory --version 
hishtory version v0.265
```

When I run command that have newlines they work and are added to the history list fine: 
![hishtory-newline-1](https://github.com/ddworken/hishtory/assets/1915791/ea8008c7-4c01-464a-9391-8272e013ddfd)

However, when that same command is then run, the newline is printed to the terminal literally, causing the command to break:
![hishtory-newline-2](https://github.com/ddworken/hishtory/assets/1915791/be89c636-b0e5-4205-9e6f-dabce9defe7f)

I assume this is an escaping issue somewhere, but im not sure where it would be.

**Comment by ddworken** [comment]
Ah, thank you for pointing this out! I had run into this once on my own, but forgotten to follow up. #170 should fix this, I'll re-ping this issue once that gets merged and released.

**Comment by ddworken** [comment]
Ok, this is now fixed and released! Thank you again for pointing this out, and if you spot any other issues, please let me know!
