### ISSUE TITLE
Install does not work

### ISSUE THREAD

**Issue by github-cli** [ddworken/hishtory#173]
after I install via the install.py, I can open a new ssh session (bash) to the ubuntu machine and hishtory will not work in user mode.

this is on Ubuntu 22.04.3

btw, is there a way to check which url hishtory is syncing with?

**Comment by github-cli** [comment]
update: found the issue...
the install creates a /tmp/hishtory-client file which the next user trying to install hishtory cannot delete as it belongs to the last user who installed it....
install script fails because it couldnt overwrite the file... probably an issue with the install script not cleaning up the tmp directory

**Comment by ddworken** [comment]
Ah, thank you for the issue! I actually had just noticed this earlier today myself and it is now fixed. :)
