### ISSUE TITLE
Support for custom OpenAI endpoint?

### ISSUE THREAD

**Issue by artivis** [ddworken/hishtory#186]
Hello,

Would it be possible to extend the AI support? Especially to offer the possibility to hit self-hosted instances.
I guess the first low hanging fruit would be to make the OpenAI endpoint and model parameterizable.
This would allow to hit OpenAI compatible projects such as [ollama](https://ollama.com/blog/openai-compatibility).

Thanks.

**Comment by ddworken** [comment]
Thanks for opening this issue! This has now been implemented and released (run `hishtory update` to get the latest version). You can configure a custom AI API endpoint via `hishtory config-set ai-completion-endpoint https://your-openai-compatible-endpoint.example/path`. If you run into any issues with this, please let me know
