### ISSUE TITLE
Support horizontal scrolling for all table columns

### ISSUE THREAD

**Issue by hongyi-zhao** [ddworken/hishtory#188]
How can I let **hishtory** display very long directories and commands, as shown below?

![image](https://github.com/ddworken/hishtory/assets/11155854/1bc7a04d-633a-46fa-bbfc-8194c4936557)

Regards,
Zhao

**Comment by ddworken** [comment]
Currently, it is possible to horizontally scroll the command by pressing `shift` and either left/arrow keys (this is visible in the help page that you can see via `control+h`). Though it currently isn't possible to horizontally scroll for other columns, so we can make this issue a feature request to support this.

**Comment by ddworken** [comment]
This is now available in the latest release, if you run `hishtory update` it will be possible to horizontally scroll through the table via shift+left/right.

**Comment by hongyi-zhao** [comment]
Another idea is to allow detailed information to be displayed directly in a separate window for the selected/highlighted entry.
