### ISSUE TITLE
Document Mixed Offline/Online Behavior

### ISSUE THREAD

**Issue by matthewcmead** [ddworken/hishtory#19]
Can you document the behavior if the self-hosted (or public) backend is not available while hishtory is active during a shell session?  Will history events be relayed as soon as network connectivity returns?  Will errors be thrown while offline?

Thank you for an innovative capability.

**Comment by ddworken** [comment]
Fixed in 1de0e60. https://blog.daviddworken.com/posts/hishtory-explained/ has the full details on how syncing works with going offline. 

But the tl;dr is that it behaves optimally while offline: Saving history entries and relaying them once network connectivity returns.

**Comment by matthewcmead** [comment]
Wow, this is a great explanation.  Thanks for posting it and for putting a really nifty tool out there.
