### ISSUE TITLE
demo.gif plays too quickly to read / follow

### ISSUE THREAD

**Issue by gene1wood** [ddworken/hishtory#199]
The [`demo.gif`](https://github.com/ddworken/hishtory/blob/master/backend/web/landing/www/img/demo.gif) plays pretty quickly. I found it difficult to follow what was going on to see how hishtory works. It may be worth replacing this with the same thing but just running at normal speed (not sped up)

**Comment by ddworken** [comment]
Thanks for the feedback! I think you're right, it really is a bit too fast to understand. I slowed it down a good bit, though if you think it is still too fast, please do let me know.

**Comment by gene1wood** [comment]
@ddworken Thanks! I watched the gif and it did take me about 10 viewings to actually follow what was going on in the demo.

I would honestly slow it down further. Another thing that could make it more understandable is if the recording was of two different terminal windows, one for each host. It took me a number of viewings to realize that in the demo you're showing running a command on one server, sshing to another server and then entering the hishtory search UI on that other server.

So ya, this is better, but I'd honestly slow it by half again.

![demo-half-speed](https://github.com/ddworken/hishtory/assets/1134034/f2d0447c-2dbe-46f5-8094-faf2462f487a)
