### ISSUE TITLE
Cannot locate `.hishtory.db` file

### ISSUE THREAD

**Issue by Olshansk** [ddworken/hishtory#21]
The main `README.md` says:

<img width="881" alt="Screen Shot 2022-11-06 at 9 07 44 PM" src="https://user-images.githubusercontent.com/1892194/200230811-6fc1b2de-8fb4-4cf2-afd8-eda560f06db5.png">

I've been trying to find it in my local workspace but it doesn't seem to exist:

<img width="1028" alt="Screen Shot 2022-11-06 at 9 08 38 PM" src="https://user-images.githubusercontent.com/1892194/200230897-0d032795-5d43-4ad3-87b5-3e883a8e415d.png">

Any pointers are appreciated!

**Comment by ddworken** [comment]
It is in `~/.hishtory/.hishtory.db`:

```
david@Davids-MacBook-Air hishtory % sqlite3 ~/.hishtory/.hishtory.db
SQLite version 3.37.0 2021-12-09 01:34:53
Enter ".help" for usage hints.
sqlite> .schema
CREATE TABLE `history_entries` (`local_username` text,`hostname` text,`command` text,`current_working_directory` text,`exit_code` integer,`start_time` datetime,`end_time` datetime,`device_id` text, `home_directory` text, `custom_columns` blob);
CREATE UNIQUE INDEX `compositeindex` ON `history_entries`(`local_username`,`hostname`,`command`,`current_working_directory`,`exit_code`,`start_time`,`end_time`,`device_id`);
sqlite>
```

Let me know if you're still having issues finding it!

**Comment by Olshansk** [comment]
@ddworken Works! Didn't realize it was a dot file :)

One quick follow unrelated follow up: is it possible to index my previous history into hishtory?
