### ISSUE TITLE
How to disable debug log?

### ISSUE THREAD

**Issue by h0tw1r3** [ddworken/hishtory#211]
Grows exponentially compared the commands being entered. Is there a way to disable the log, or at least reduce the log level from info?

**Comment by ddworken** [comment]
Hmm, are you seeing the log growing unbounded? In theory, it is [configured so that that shouldn't happen](https://github.com/ddworken/hishtory/blob/master/client/hctx/hctx.go#L42-L47) so I'd be surprised if this is happening.

**Comment by h0tw1r3** [comment]
That's good to know. My concern was more that it's just very noisy, and (for me / general use cases?), not helpful in most cases. On a system with a slow disk (raspberry pi types) there's a noticeable slowdown.
