### ISSUE TITLE
Feature request: cached history

### ISSUE THREAD

**Issue by cowboygneox** [ddworken/hishtory#22]
This work is amazing.

One thing I noticed is that Ctrl-R replacement is awesome, but still has noticeable (though small) lag compared to the original Ctrl-R. Seems like an in-memory cache would resolve that issue.

An idea: when hishtory is enabled:

* Ctrl-R queries the in-memory cache (load the last X entries or something)
* Hit Ctrl-R a second time to query the full history in SQLite

Thoughts?

**Comment by cowboygneox** [comment]
This is making the assumption that this is the "slow" part of `tquery`: https://github.com/ddworken/hishtory/blob/9d26e70f838df6a01710d719254ec179c09861f4/client/lib/tui.go#L393

**Comment by cowboygneox** [comment]
A couple other ideas:

* Load the table async
* Don't populate initial values and only search

However, the search is query fast once the `tquery` has loaded. Is it the `tui` that's messing with us here?

**Comment by cowboygneox** [comment]
Now I'm rambling, but maybe it's the db opening?

https://github.com/ddworken/hishtory/blob/9d26e70f838df6a01710d719254ec179c09861f4/client/hctx/hctx.go#L107

I probably should just check out the code and profile it. Sorry for spamming.

**Comment by ddworken** [comment]
Thank you for opening this! I dug in and it turns out it was a silly mistake on my end: I was processing all deletion requests before displaying the table. This meant displaying the table was blocking on a HTTP request. ^ fixes it (and I'll get that out in a release very soon).

**Comment by cowboygneox** [comment]
@ddworken Awesome! I'm happy that my rambling lead to something legitimately useful. :)

I love this project. Please let me know if you need any help.

**Comment by cowboygneox** [comment]
Just pulled the latest version, it's so much better :) Thanks again!
