### ISSUE TITLE
Doesn't work well with 'screen' and other multiplexers.

### ISSUE THREAD

**Issue by ildus** [ddworken/hishtory#221]
Thanks for the project!
It works great usually, but when I try to run it under screen I get this

```
Warning: failed to search: search query contains unknown search atom '11;rgb' that doesn't match any column names

Search Query: > 11;rgb:1c1c/1c1c/1c1c
```

**Comment by ddworken** [comment]
Ah interesting, I just tried this in screen from both macos and ubuntu and I didn't run into this behavior. Can you tell me what shell version, screen version, and OS you're observing this behavior with?

**Comment by ildus** [comment]
@ddworken I think it's related with kitty terminal which I'm using: https://sw.kovidgoyal.net/kitty/color-stack/#querying-current-color-values

**Comment by ddworken** [comment]
Ah interesting, that does seem quite possible. I just installed kitty to try this out but even with kitty + screen on macos I can't seem to reproduce this. Can you share a bit more information on what OS/software versions you're using? And is it just when you press control-R from a screen session in kitty?

**Comment by ildus** [comment]
It is in Fedora 40, screen version 4.09, zsh 5.9 with oh-my-zsh.
Yes, it is really easy to reproduce: just ctrl+R under screen session in kitty.

**Comment by ddworken** [comment]
Hmm, have you overridden the `TERM` variable? When I try to start screen within kitty I get the error message:

```
Cannot find terminfo entry for 'xterm-kitty'.
```

This seems to be resolved if I set the `TERM` variable to a variety of other known values, but I'm guessing you might have it set to some specific value that is causing this issue.

**Comment by ildus** [comment]
@ddworken Yeah, I remember having problems with `xterm-kitty` so I set `TERM=xterm-256color `.

**Comment by ddworken** [comment]
Got it, can you run `hishtory update` and let me know whether [6fd624f](https://github.com/ddworken/hishtory/commit/6fd624f32c14b18dd067a5c8fad3e5838bceefbb) properly fixes your issue?

**Comment by ildus** [comment]
@ddworken Thanks! I don't see the problem anymore.
