### ISSUE TITLE
update tmp file permission conflict

### ISSUE THREAD

**Issue by AndCycle** [ddworken/hishtory#227]
```
$ hishtory update
2024/07/11 13:01:52 hishtory v0.297 fatal error at github.com/ddworken/hishtory/client/cmd/update.go:28: failed to delete file /tmp/hishtory-client when trying to download a new version
```
`hishtory update` left update file at `/tmp`
different user will conflict each other on doing update due to file permission issue

need to create safe tmp directory for update work to prevent other possible issue

**Comment by ddworken** [comment]
Ah, thanks for this! I updated hishtory to make sure it always cleans up that file which should avoid this issue.

**Comment by AndCycle** [comment]
I have no experience with go lang, after some googling I think you can use `os.MkdirTemp` to make a proper working tmp folder to work with then `os.RemoveAll` to clean up
