### ISSUE TITLE
Changing OpenAI model

### ISSUE THREAD

**Issue by temperatio** [ddworken/hishtory#230]
Hello,

Could we have the option to switch the OpenAI model in use? OpenAI periodically releases new and improved models, and it would be very useful to be able to change the model through environment variables or configuration settings.

Thank you.

**Comment by GRbit** [comment]
Hi @temperatio !
I did this, but only for server side (since I'm self hosting everything).

https://github.com/ddworken/hishtory/pull/231

It's not clear for me if your request is about being able to change model on server side or on client side. Can you please clarify?

**Comment by ddworken** [comment]
Thanks for the PR for this @GRbit! I merged #231 and also added support for configuring this for the client via the same `OPENAI_API_MODEL` environment variable. I don't really expect many people to need to configure this, so I'm not planning on exposing it as a config option, but feel free to set it for yourself (e.g. `export OPENAI_API_MODEL=gpt-40` in your bashrc).
