### ISSUE TITLE
the install subcommand should check for the .profile file

### ISSUE THREAD

**Issue by dgsb** [ddworken/hishtory#238]
in bash environment there are two potential login shell config file: `bash_profile` and `.profile`.
when the `.profile` exists, the install subcommand writes its config in the `.bash_profile` and creates this new file which override the user config defined in `.profile`

**Comment by ddworken** [comment]
Thanks for opening this issue! As I understand it, `.profile` is meant for any bourne-compatible shell and will thus be read by multiple different shells (e.g. zsh will read it). Whereas our shell config actually is bash-specific and if we started putting it in `.profile` it would break zsh. See [here](https://unix.stackexchange.com/questions/45684/what-is-the-difference-between-profile-and-bash-profile). 

Given this, I'm wondering: Can you expand on the issue you're running into with this overridding the user config in `.profile`? Is putting this in `.bash_profile` causing bash to start ignoring your `.profile` file? Or is something else going wrong here?

**Comment by dgsb** [comment]
> Is putting this in .bash_profile causing bash to start ignoring your .profile file?

This is exactly what is happening the `.profile` file is ignored upon `.bash_profile` creation.
I'm not expert all bourne shells variations and the expected behaviour, with more context I'm not sure what would be a correct fix for that.

I can manually patch the `.bash_profile` which then source the `.profile` file. But other users may have their configuration broken by a brand new `bash_profile` creation.

Can we force the `source .profile` entry if the `.bash_profile` is created ?

**Comment by ddworken** [comment]
Got it, that all makes sense. I think #240 is the right approach for this then, I'll get that PR landed. Thank you for the bug report and the detailed discussion!
