### ISSUE TITLE
Question: Where is the default backend hosted?

### ISSUE THREAD

**Issue by ricardosllm** [ddworken/hishtory#25]
Hi, firstly thanks for a great tool and project!

It's mentioned on the README the options to self host but I can't find anything, here or in hishtory.dev, about where it's currently hosted, so where is it hosted? Is there an org behind the project? 

Thank you.

**Comment by ddworken** [comment]
It is hosted on a DigitalOcean droplet in their SFO2 region. It is mapped to the domain `api.hishtory.dev`. It is just hosted by me, a random engineer who enjoys making things. Ultimately if the server does go down for any reason, hishtory will continue to work but syncing will break until you configure an alternate server. 

Let me know if you have any other questions!
