### ISSUE TITLE
New hishtory version give random letters on new line after command

### ISSUE THREAD

**Issue by roland-5** [ddworken/hishtory#253]
I didn't have this problem before, but after updating `hishtory` after every command I do, there are random letters and signs. I don't remember what version was still good - maybe 309.
If I comment out `blesh` from bash config file, everything is good, but if I enable `blesh` again a got this every time:
![ps_20240922195746](https://github.com/user-attachments/assets/2e63713f-befd-435a-a3e8-4cfcccb96e08)

In fish, even if config file is empty and I add only `hishtory` to it, it gives the same problems:
![ps_20240911170952](https://github.com/user-attachments/assets/f78b0830-40b4-479a-869e-d3281beacd90)

![ps_20240927053459](https://github.com/user-attachments/assets/8d3a6614-2bc6-4e78-b395-4f7eb74acc34)

If I just enter without command, nothing bad happens. I tried Alacritty and Wezterm as terminals and its the same effect in both of them.

**Comment by ddworken** [comment]
Interesting... I tried to reproduce this and am unable to reproduce this. Those look like sort of terminal escape codes related to colors. Can you share:

* What OS you're using?
* What shell versions you're using?
* The value of the `TERM` environment variable?

If you're willing, you could also try to figure out exactly which version caused this issue by using `HISHTORY_FORCE_CLIENT_VERSION` to bisect the breakage. For example, `HISHTORY_FORCE_CLIENT_VERSION=v0.309 hishtory update` to roll back to version 309.

**Comment by roland-5** [comment]
Ups, sorry, I forgot about it.
- Arch Linux
- GNU bash, version 5.2.37(1)-release (x86_64-pc-linux-gnu)
- blesh-git 0.4.0_devel4.r2203.32f290df-1 (from AUR)
- fish, version 3.7.1
- `TERM` for Alacritty: `alacritty`
- TERM` for Wezterm: `xterm-256color`
- TERM` for Foot: `foot`

I toyed with different version of `hishtory` and last one that doesn't vomit escape codes is `304`. From `305` there is escape codes nightmare for bash with blesh-git and even clear fish in every mentioned above terminals.

PS. This force client command is really handy, thanks.
