### ISSUE TITLE
Add API/flags to import richer history files

### ISSUE THREAD

**Issue by Alives** [ddworken/hishtory#263]
I have over a decade of shell logs with timestamp, user, cwd recorded.  I wanted to import all these as well (and not with the same timestamp and cwd).  I ended up writing a script to directly add them to the db, but would have preferred if the tool could accept a flag or env var to custom set the parameters for each command entry instead of just setting them to whatever the local and current environment dictated.

Add some ability to custom set CWD, Timestamp, User and the ability to import commands one by one?

**Comment by ddworken** [comment]
Ah, this is a fair point! I've been pondering how I might support this, and I was wondering: Would it be easy for you to convert your shell history logs to some sort of standardized-ish format for imports? E.g. something like:

```
{"cmd": "ls", "cwd": "/home/david/", "timestamp": 1734071227}
{"cmd": "echo x", "cwd": "/home/david/", "timestamp": 1734071227}
```

It seems like it could be reasonable to have a feature to import JSON-formatted history entries, and then people could generate these however they'd like. What do you think?

**Comment by Alives** [comment]
That works for me!  One issue is the escaping of `"` for any of them in the commands but a JSON library would handle it just fine.

**Comment by ddworken** [comment]
Ok, this is now supported with the import-json and export-json commands! PTAL and let me know if you have any other suggestions or feedback.
