### ISSUE TITLE
hishtory status should show all config options

### ISSUE THREAD

**Issue by Alives** [ddworken/hishtory#264]
It would be good to know if offline is enabled or not, among other .hishtory.config options.

**Comment by ddworken** [comment]
If you run `hishtory status -v` you'll see a line that looks like `Sync Mode: Enabled` saying whether or not syncing is enabled. Though I think you are right that it might be useful to have an output that includes all the hishtory config options, #266  will add this.

**Comment by ddworken** [comment]
If you run `hishtory update`, the `hishtory status --full-config` flag will now work. Please do let me know if you have any other feedback or thoughts on hishtory!
