### ISSUE TITLE
Dedicated offline only binary

### ISSUE THREAD

**Issue by Alives** [ddworken/hishtory#265]
It would be good to add a binary with no network abilities at all to guarantee no "online" mode features would be possible.  I know there is offline mode, but I would prefer to know that there is no possibility of network communication.

**Comment by jyoung15** [comment]
I agree with this.  The most secure settings should be the default, which means offline mode and turn off AI shell assistance.  Let users opt-in if they want these features.  The README could do a better job of explaining that your data is sent to https://api.hishtory.dev (even if encrypted).

**Comment by ddworken** [comment]
Thanks for the feedback! I am open to providing a binary with no network capabilities at all, but I'm wondering: Do you think this binary should also have the ability to run `hishtory update` stripped out? As I personally see it, the syncing, AI integration, and secure updates are key parts of hishtory that I get the most utility out of. So I'm curious to understand whether you'd truly want a binary with all of those features completely disabled? 

If so, I think that should be relatively simple to do, so I'm happy to add support for that.

**Comment by ddworken** [comment]
Ok, this is now fully supported with the `offline` tag. Check out https://github.com/ddworken/hishtory/blob/master/docs/offline-binary.md for more info. If you run into any issues with this or have any other suggestions, please let me know!
