### ISSUE TITLE
[Support] fish with oh-my-fish

### ISSUE THREAD

**Issue by raguay** [ddworken/hishtory#3]
It would be great to support the fish shell and the oh-my-fish setting of the prompt.

**Comment by raguay** [comment]
I forgot, I use the oh-my-posh in fish to generate the command line status/prompt. I think it would need to work with it's format.

**Comment by ddworken** [comment]
Added! v0.147 now supports fish. If you already have hishtory installed, you can update via `hishtory update` and it will automatically configure fish to use hishtory.

**Comment by raguay** [comment]
That works great. Thanks.
