### ISSUE TITLE
How to unistall hishtory?

### ISSUE THREAD

**Issue by victorhck** [ddworken/hishtory#32]
Maybe it's a silly question, but... If I try hishtory and after testing I want to go back, how can I unistall it?
thanks for your work!

**Comment by ddworken** [comment]
See "Uninstalling" in the readme. And please reopen if you have any other questions!

**Comment by victorhck** [comment]
> See "Uninstalling" in the readme. And please reopen if you have any other questions!

OMG! Sorry for that silly question, I didn't saw that menu...
Greetings...
