### ISSUE TITLE
Better support for multiline commands

### ISSUE THREAD

**Issue by calexicoz** [ddworken/hishtory#34]
Hi again 👋

I noticed that `hishtory` does not handle multiline well. Specifically, if I edit a long command line like this:

```
command \
  --param A \
  --param B \
| filter1 \
| filter2
```

When recalled, it will come back as:

```
 command \   --param A \   --param B \ | filter1 \ | filter2
```

I thus have to remove all the `\` chars, or re-edit it to bring it multiline again. For complex commands, the ability to break over multiple lines coupled with `CTRL+X CTRL+E` is very helpful.

**Comment by ddworken** [comment]
+1 to this feature request. :) Currently this does work well if you use `hishtory query`:

<img width="856" alt="Screen Shot 2022-11-16 at 9 02 26 PM" src="https://user-images.githubusercontent.com/5304541/202360521-18d15c92-2bb2-469a-ab68-876295eab5d6.png">

But it doesn't work well with the TUI view used for control-r. This is currently also tracked [here](https://github.com/ddworken/hishtory/blob/ecbbcf533abcd75e3b9bada737b40a851bc9332c/client/lib/tui.go#L231). 

I essentially need to replicate [this change](https://github.com/rodaine/table/compare/master...ddworken:table:master) that I made to rodaine/table, except for bubbletea.

**Comment by ddworken** [comment]
Ah! This is a good point, that would actually be a good bit easier to implement. And in the table I could even just display it as `\n`, since this is tool for programmers who would hopefully understand that. Thank you for that suggestion, I'll go for that instead.

**Comment by ddworken** [comment]
I dug into this, and frustratingly it seems like it isn't possible for the control-r search to return a value containing newlines (just a limitation of zsh). But I realized that an almost as good solution is to just replace newlines with semicolons, so at least the command can properly run. That is what ^ does. WDYT of that as a solution?

**Comment by asciithoughts** [comment]
Mmm. I'm not sure that is better. Wouldn't that transform this:

```
command \
  --param1 \
  --param2
```

Into this:

```
command; --param1; --param2
```

Effectively breaking the command?

I use [atuin](https://github.com/ellie/atuin) as well, and it pastes newlines fine (using `CTRL+R` too). Not sure how though. Maybe it has to do with the [hook](https://github.com/ellie/atuin/blob/f93da455a354f019213315d93bd204a87245b928/src/shell/atuin.zsh#L29-L46).

**Comment by asciithoughts** [comment]
\o/ Thanks!
