### ISSUE TITLE
Healthcheck endpoint issues

### ISSUE THREAD

**Issue by RickyGrassmuck** [ddworken/hishtory#35]
Just setup the server and while attempting to verify I had my proxy and everything setup right using the /healthcheck endpoint, I found that, unless the server finds more than 100 entries in the devices table, the endpoint does not provide a response and the server panics with a message about there not being enough devices.

```
hishtory-hishtory-1  | 2022/11/16 04:35:15 http: panic serving 192.168.1.100:38760: Suspiciously few devices!
hishtory-hishtory-1  | goroutine 131 [running]:
hishtory-hishtory-1  | net/http.(*conn).serve.func1()
hishtory-hishtory-1  |  /usr/local/go/src/net/http/server.go:1825 +0xbf
hishtory-hishtory-1  | panic({0xa406a0, 0xbbf770})
hishtory-hishtory-1  |  /usr/local/go/src/runtime/panic.go:844 +0x258
hishtory-hishtory-1  | main.healthCheckHandler({0xbc51d8, 0xc00200e0d8}, 0x415c45?)
hishtory-hishtory-1  |  /go/backend/server/server.go:352 +0x15f
hishtory-hishtory-1  | main.withLogging.func1({0xbc5418?, 0xc000734540}, 0xc000296600)
hishtory-hishtory-1  |  /go/backend/server/server.go:616 +0x111
hishtory-hishtory-1  | net/http.HandlerFunc.ServeHTTP(0x7f6b1c311318?, {0xbc5418?, 0xc000734540?}, 0x415c45?)
hishtory-hishtory-1  |  /usr/local/go/src/net/http/server.go:2084 +0x2f
hishtory-hishtory-1  | net/http.(*ServeMux).ServeHTTP(0x0?, {0xbc5418, 0xc000734540}, 0xc000296600)
hishtory-hishtory-1  |  /usr/local/go/src/net/http/server.go:2462 +0x149
hishtory-hishtory-1  | net/http.serverHandler.ServeHTTP({0xc0001e55c0?}, {0xbc5418, 0xc000734540}, 0xc000296600)
hishtory-hishtory-1  |  /usr/local/go/src/net/http/server.go:2916 +0x43b
hishtory-hishtory-1  | net/http.(*conn).serve(0xc0000c28c0, {0xbc5bc0, 0xc000314f00})
hishtory-hishtory-1  |  /usr/local/go/src/net/http/server.go:1966 +0x5d7
hishtory-hishtory-1  | created by net/http.(*Server).Serve
hishtory-hishtory-1  |  /usr/local/go/src/net/http/server.go:3071 +0x4db
```

Since this endpoint is typically used for checking the a service has started and is in a "healthy" state, it would probably be more useful if this endpoint simply checked that the db is connected and use that to determine the response(ok or failed) and make sure that a response to the incoming request is always given so that the client hitting the endpoint gets the correct status from the server.

loving the project so far, looking forward to diving in more!

**Comment by ddworken** [comment]
Ah thank you for this feedback! I agree. :) Though I want to keep those checks for my own production instance, so I tweaked the code to only require this if the `Host` header is `api.hishtory.dev`.
