### ISSUE TITLE
Ctrl-R issues on macOS with bash

### ISSUE THREAD

**Issue by richjames0** [ddworken/hishtory#37]
I love this tool - thanks for all the work!

Unfortunately I'm having some problems with it on macOS, under both iTerm2 and macOS Terminal:
- Ctrl-R correctly shows the UI for picking a command but - when I press return - I just go back to an empty prompt (the command isn't populated as it is on Linux)
- I can't uninstall Ctrl-R integration either. If I run `hishtory config-set enable-control-r false`, as in the README, it appears to work but then when I next Ctrl-R I get `hishtory fatal error at github.com/ddworken/hishtory/client/cmd/query.go:46: search query contains unknown search atom https` and then the next time I Ctrl-R I'm back to the hishtory UI

**Comment by ddworken** [comment]
> Ctrl-R correctly shows the UI for picking a command but - when I press return - I just go back to an empty prompt (the command isn't populated as it is on Linux)

What shell are you using? And if it is zsh (the default on macOS), can you share the output of `zsh --version`? 

> I can't uninstall Ctrl-R integration either. If I run hishtory config-set enable-control-r false, as in the README, it appears to work but then when I next Ctrl-R I get hishtory fatal error at github.com/ddworken/hishtory/client/cmd/query.go:46: search query contains unknown search atom https and then the next time I Ctrl-R I'm back to the hishtory UI

Hmm, do you restart your termianl after disabling the control-r integration? This is required (though I should make sure to document that).

**Comment by richjames0** [comment]
Thanks for the quick response! I wasn't restarting shell after unhooking Ctrl-R, so I'll try that.

I'm using bash on macOS (changed from the default). See version below - perhaps it's an issue with the old Apple build?

```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by ddworken** [comment]
Ah, yes. This is an issue with the old version of bash that macOS ships. If you want it to work with bash, you'll have to use bash >5. If you do `brew install bash` it will install 5.2 which works with hiSHtory (and is what I test with). 

Leaving this issue open and I'll get this documented.

**Comment by richjames0** [comment]
Unfortunately I'm seeing the same issue with updated bash:

```
GNU bash, version 5.2.9(1)-release (x86_64-apple-darwin21.6.0)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

Ctrl-R removal does work when I start a new session though :)

**Comment by ddworken** [comment]
> Unfortunately I'm seeing the same issue with updated bash:
> 
> ```
> GNU bash, version 5.2.9(1)-release (x86_64-apple-darwin21.6.0)
> Copyright (C) 2022 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> ```

Hmm, are you sure the session you're in is using the new version of bash? You can check via `echo $BASH_VERSION`. That version of bash is the exact one I have on my macbook that I'm testing with.

**Comment by richjames0** [comment]
Ah hahah apparently not - great call. Installing via brew didn't set it as the default shell, I guess.

For posterity - I had to add the newly installed shell (via `which bash` and at `/usr/local/bin.bash` for me) to `/etc/shells` and then chsh to the same.

Now finally Ctrl-R works (re-enabled with `hishtory config-set enable-control-r true`)

Thanks for all the help, David.

**Comment by grosser** [comment]
FYI for updating shell this article worked https://www.shell-tips.com/mac/upgrade-bash/#gsc.tab=0
but  I has to use `/opt/homebrew/bin/bash`
