### ISSUE TITLE
Setup fails with a server error

### ISSUE THREAD

**Issue by hutattedonmyarm** [ddworken/hishtory#38]
When installing, setup fails with the message `failed to register with backend: failed to GET https://api.history.dev/api/v1/register?user_id=XXX&device_id=XXX: status_code=502`

**Comment by ddworken** [comment]
Ah thank you for filing this bug!!! My DB had run out of storage and this broke new installs. I've fixed this (so please try again!) and set up monitoring so that I'll get alerted if this ever happens again.

**Comment by jmauro** [comment]
Hello, 

I just hit the same error when initiating a new device:
```
Setting secret hishtory key to XXXXXXXXXXXXX
2025/01/06 22:38:03 hishtory v0.324 fatal error at github.com/ddworken/hishtory/client/cmd/install.go:98: failed to bootstrap device from the backend: failed to GET https://api.hishtory.dev/api/v1/bootstrap?user_id=XXXXXXXXXXXXXXXX=&device_id=XXXXXXXX: status_code=502
```

And to be honest I feel a bit helpless and don't know information should I provide to you to help debugging.


Kind regards,
JM

**Comment by ddworken** [comment]
Hmm, I just went through creating and setting up a new device and didn't run into this. Does this error reproduce reliably for you? If so, could you provide me with the `user_id` value (either here, or you can email it to me at `david@daviddworken.com`) so I can take a closer look through the logs?
