### ISSUE TITLE
onboarding: should only add to .bash_profile or .bashrc

### ISSUE THREAD

**Issue by grosser** [ddworken/hishtory#41]
I have both and it got added to both which seems like a bug
... I removed one and it still worked fine

**Comment by ddworken** [comment]
See #14, this is intentional to work around some weird behavior that macOS's default terminal has. Did it cause any issues for you to have it in both? There is an explicit include guard, so in my own testing it is fine to have it in both (and doing so ensures it is always executed by bash).

**Comment by grosser** [comment]
should be fine then ... just seemed like an obvious bug
