### ISSUE TITLE
Config file corrupts itself

### ISSUE THREAD

**Issue by plotnw** [ddworken/hishtory#47]
Sometimes on restarting my computer all my prompts give the warning
```
panic: failed to retrieve config: failed to parse config file: invalid character ':' after top-level value

goroutine 1 [running]:
github.com/ddworken/hishtory/client/hctx.MakeContext()
        github.com/ddworken/hishtory/client/hctx/hctx.go:113 +0x396
github.com/ddworken/hishtory/client/cmd.glob..func8(0x2d88340?, {0x1c0c26c?, 0x0?, 0x0?})
        github.com/ddworken/hishtory/client/cmd/configGet.go:27 +0x2e
github.com/spf13/cobra.(*Command).execute(0x2d88340, {0x2ddcf00, 0x0, 0x0})
        github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2d86f20)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
github.com/ddworken/hishtory/client/cmd.Execute()
        github.com/ddworken/hishtory/client/cmd/root.go:22 +0x25
main.main()
        github.com/ddworken/hishtory/hishtory.go:8 +0x17
```

Looking at the config file (with keys zeroed out), the issue seems to be that the end of the config is duplicated 
```
{"user_secret":"00000000-0000-0000-0000-000000000000","is_enabled":true,"device_id":"000000000-0000-0000-0000-000000000000","last_saved_history_line":"  501  nvim TODO.rst","have_missed_uploads":false,"missed_upload_timestamp":0,"have_completed_initial_import":true,"enable_control_r_search":true,"displayed_columns":["CWDd","Timestamp","Exit Code","Command"],"custom_columns":[{"column_name":"CWDd","column_command":"pwd"},{"column_name":"CWDs","column_command":"echo $(pwd)END"}],"is_offline":true,"filter_duplicate_commands":false,"timestamp_format":"Jan 2 2006 15:04:05 MST"}:04:05 MST"}

```
 I'm not quite sure what the behavior which causes this is -- it only occurs on restarting my computer, does not always occur, and I the amount duplicated varies. For example, 
```
{"user_secret":"00000000-0000-0000-0000-000000000000","is_enabled":true,"device_id":"000000000-0000-0000-0000-000000000000","last_saved_history_line":"  501  nvim ref.bib","have_missed_uploads":false,"missed_upload_timestamp":0,"have_completed_initial_import":true,"enable_control_r_search":true,"displayed_columns":["CWDd","Timestamp","Exit Code","Command"],"custom_columns":[{"column_name":"CWDd","column_command":"pwd"},{"column_name":"CWDs","column_command":"echo $(pwd)END"}],"is_offline":true,"filter_duplicate_commands":false,"timestamp_format":"Jan 2 2006 15:04:05 MST"}T"}
```
also is an example, and here only the `T"}` part is duplicated.
 
 
 I think one time the duplicated part appeared twice, so something of the form
`15:04:05 MST"}:04:05 MST"}:05 MST"}`
though I do not have the exact text if it in fact occurred. I can update with more examples of the config if it occurs.

I initially thought the length of "last_saved_history_line" could matter, but I tried running a really long command, restarting, running a short command, restarting and the error did not occur. This testing was very limited though. 

I use bash and hishtory version gives `hiSHtory version v0.185`. Let me know if any other details would be useful.

**Comment by ddworken** [comment]
Ah thank you for the detailed bug report! I never managed to reproduce this manually, but I did manage to write a test that led to config file corruption and wrote a fix for that. This is released in `v0.187` (run `hishtory update` to get it). I hope this fixes the issue for you and please reopen this if you run into any other issues!
