### ISSUE TITLE
Linux arm64(raspberry pi) Support

### ISSUE THREAD

**Issue by east4ming** [ddworken/hishtory#48]
Need linux arm64(raspberry) Support.
Thanks

**Comment by ddworken** [comment]
Done! I don't have a linux arm64 machine handy to test on, but I believe this should be all set up and working. Please reopen this issue if you run into any issues with it!

**Comment by east4ming** [comment]
> 

```bash
casey in raspberrypi
❯ curl https://hishtory.dev/install.py | python3 -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1914    0  1914    0     0   2972      0 --:--:-- --:--:-- --:--:--  2972
No hishtory binary for system=Linux, machine=aarch64!
If you believe this is a mistake, please open an issue here: https://github.com/ddworken/hishtory/issues
```
Has the one-click installation script been updated? Kindly reminder: The infrastructure code corresponding to arm64 is aarch64

Tks

**Comment by east4ming** [comment]
After install(change py script `platform.machine() == "aarch64"`) , verified.
![Linux arm64 support verified](https://user-images.githubusercontent.com/13358726/207209641-85f9248f-4e4a-42f5-bcf7-c9e2033a83d4.png)
