### ISSUE TITLE
Storing additional command context

### ISSUE THREAD

**Issue by musirisriram** [ddworken/hishtory#5]
First, this is a really great tool! I really appreciate having access to reliable, metadata-rich history.

It would be great if the tool could record more context, such as git branch/sha and environment variables. Many commands I run are very sensitive to these (and other) context parameters, so having access to them would be helpful to get back to a known state to re-run a command.

**Comment by ddworken** [comment]
Thank you for the suggestion! I actually really like this idea, and am planning on implementing it. My general idea is to approach this as two separate features:

1. Support changing the set of columns that are displayed in the table 
2. Support defining custom columns that are populated from running a specified bash command 

So in the end it will be possible to do something like:

```
hishtory add-column git_remote "git remote get-url origin"
hishtory set-columns hostname,cwd,timestamp,git_remote,cmd
```

To have a custom column named "Git Remote" containing the git remote URL for a given directory. 

No promises about when this will be implemented, but I am planning on it. :)

**Comment by ddworken** [comment]
Done! See the custom columns section in the readme
