### ISSUE TITLE
TLS Handshake Timeout

### ISSUE THREAD

**Issue by Olshansk** [ddworken/hishtory#50]
I'm not sure what happened today, but I'm seeing a lot of these errors in my terminal all the time:

```
2022/12/05 18:42:02 hishtory fatal error at github.com/ddworken/hishtory/hishtory.go:31: failed to GET https://api.hishtory.dev/api/v1/get-deletion-requests?user_id=<user_id>=&device_id=<device_id>: Get "https://api.hishtory.dev/api/v1/get-deletion-requests?user_id=<user_id>=&device_id=<device_id>": net/http: TLS handshake timeout
```
---

**EDIT**

1. This (the logs) continue even after I run `hishtory disable` and verify that it's false with `hishtory status`

2. Is there a way for me to easily revert to `zsh`'s normal `ctrl+R` when there's an issue. Right now, with `hishtory` disable, the reverse search prompt lags and nothing shows up. However, I do not want to uninstall `hishtory` altogether.

**Comment by SimDaeSoo** [comment]
If synchronization between multiple computers is not required
than how about this?

https://github.com/ddworken/hishtory#advanced-features:~:text=If%20you%20don%27t%20need%20the%20ability%20to%20sync%20your%20shell%20history%2C%20you%20can%20install%20hiSHtory%20in%20offline%20mode.

you can install hishtory offline mode.

**Comment by SimDaeSoo** [comment]
install binary (my computer is darwin arm) and run shell command
```sh
$ chmod +x hishtory-darwin-arm64
$ ./hishtory-darwin-arm64 install --offline
```

**Comment by Olshansk** [comment]
`Are you sure you want to uninstall hiSHtory and delete all locally saved history data`

I definitely want to keep my history though :)

**Comment by SimDaeSoo** [comment]
In my case, even if I uninstall hishtory, the history was alive when I reinstalled it.
look at this video
https://drive.google.com/file/d/1e3pQNDXg2ZzOYZP0i0CY-zbOQIqao5Km/view?usp=share_link

but it is **my case**
how about experimenting with a your second computer?

**Comment by Olshansk** [comment]
1. **Quick update**: this went away.

> In my case, even if I uninstall hishtory, the history was alive when I reinstalled it.

2. **Regarding keeping history after an uninstall**: seems like `~/.hishtory` is not deleted so an uninstall + install keeps it around and then starts reusing the same db.

>  how about experimenting with a your second computer?

3. I don't use it on another computer yet.

**Follow-up questions**

@ddworken The README says that `This is all stored locally and end-to-end encrypted` but given the earlier TLS error, is all the synching happening through a server that you pay for and maintain yourself?
