### ISSUE TITLE
Allow using ctrl+n and ctrl+p for up and down instead of arrow keys

### ISSUE THREAD

**Issue by JSpenced** [ddworken/hishtory#55]
I didn't see a setting for this, but would be useful as if you set your terminal to "emacs" mode which I have. Then, up and down arrow in most terminal things control moving up and down. I wish that was the case in the app. I switched over from an `fzf` reverse history search and loving this app. 

Is there a setting I missed or an easy way to do this?

**Comment by ddworken** [comment]
Sure! Currently the key bindings aren't configurable via settings, but adding emacs key bindings seems very reasonable to me. I added them so if you run `hishtory update` to update to `v0.189` you'll get the new bindings. 

If anyone else wants additional key bindings, please reopen this issue! If necessary, I'm happy to add a setting to make this user configurable.

**Comment by JSpenced** [comment]
@ddworken 
I'd take `ctrl+v` and `alt+v` which are page up and down in emacs land. Eg... in tmux in the terminal too in `copy` mode.

**Comment by JSpenced** [comment]
Thanks for this! Somehow I missed it but super useful.
