### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by vanjaoljaca** [ddworken/hishtory#6]
Not seeing an option for uninstalling this, I want my original ctrl-R back...

**Comment by ddworken** [comment]
If you just want your original ctrl-R back, see [here](https://github.com/ddworken/hishtory/blob/master/README.md?plain=1#L87-L90). 

To uninstall completely, you can `rm -rf ~/.hishtory/` and then edit your .bashrc/.zshrc/config.fish to remove the lines that reference hishtory. But I agree, this bit should be more easily supported. I'll try to get a `hishtory uninstall` command added later this week. :)

**Comment by ddworken** [comment]
This is now supported! If you run `hishtory uninstall` it will completely uninstall hishtory. If you're on an older version, run `hishtory update` to update to the latest version.

**Comment by adambutler** [comment]
@ddworken Under ZSH uninstalling produces an error:

```
2022/11/03 09:01:54 hishtory fatal error at github.com/ddworken/hishtory/hishtory.go:99: open /Users/adambutler/.config/fish/config.fish: no such file or directory
```

**Comment by ddworken** [comment]
Ah, thank you for catching this! I just pushed v0.165 which fixes this (it should be available to `hishtory update` within a few minutes).

**Comment by vanjaoljaca** [comment]
Thanks for the quick reply. The issue I had was that my original ctrl-R list of commands did not appear in hishtory and I had work I needed to do...
I figure if I leave this running in the background eventually it will build up a repository and I can try transition later.

**Comment by ddworken** [comment]
> Thanks for the quick reply. The issue I had was that my original ctrl-R list of commands did not appear in hishtory and I had work I needed to do...

Huh, interesting! It should have imported it when you initially installed. Do you have your history stored in a non-standard file? You can trigger another import by piping your current shell history into `hishtory import` (e.g. `cat ~/your_history_file | hishtory import`). 

> I figure if I leave this running in the background eventually it will build up a repository and I can try transition later.

Yeah, if the above doesn't work for some reason (please let me know if it doesn't!) then this also works.

**Comment by dennispan** [comment]
@ddworken Thanks for providing the option to uninstall! I tried uninstalling it, and now I'm getting this every time I ssh to the host
```
-bash: /home/dennis.pan/.hishtory/config.sh: No such file or directory
```
Any idea?
