### ISSUE TITLE
New platform request RPi3 [armv7l - 32bits]

### ISSUE THREAD

**Issue by matbgn** [ddworken/hishtory#63]
Hi,

Thanks for this amazing tool!

I'm in a position where I want now propagate the deployment to further machines in our team. So, would it be possible to build/release also the armhf version?

Again, thanks a lot and happy new year!

Some additional infos:
```
uname -a
Linux hostname 5.15.0-1021-raspi #23-Ubuntu SMP PREEMPT Fri Nov 25 15:31:29 UTC 2022 armv7l GNU/Linux
```

**Comment by ddworken** [comment]
I believe that 27cd544524ada0019d918cf3b115dd363e5e4f9a should fix this. Please give it a try and reopen this issue if you have any problems with it!

**Comment by matbgn** [comment]
AMAZING! It works like a charm so far! A big thank you :heart:
