### ISSUE TITLE
TUI broken when I have a '-' in written in my search query

### ISSUE THREAD

**Issue by adRn-s** [ddworken/hishtory#67]
- Writting "ls -" and pressing CTRL+R gets me:

```

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/ddworken/hishtory/client/lib.makeTableColumns(0xc000819fb0?, {0xc0000905a0?, 0x6, 0x6}, {0xc00085fc00, 0x64, 0x11?})
        github.com/ddworken/hishtory/client/lib/tui.go:264 +0x566
github.com/ddworken/hishtory/client/lib.makeTable(_, {_, _, _})
        github.com/ddworken/hishtory/client/lib/tui.go:333 +0xd7
github.com/ddworken/hishtory/client/lib.TuiQuery(0xc0000a4b50, {0x1ebc5e0, 0x28}, {0x7fff3ad44415, 0x4})
        github.com/ddworken/hishtory/client/lib/tui.go:397 +0x11f
main.main()
        github.com/ddworken/hishtory/hishtory.go:39 +0x1fec

```

- Pressing Ctrl+R on an emtpy shell, allows me to type "ls -" and search without issues.

- Same goes to any other command, if you stop it right next to a dash, you get the error. Oddly, typing "ls --" and pressing CTRL+R didn't throw the error 😮 

Platform: centos7

**Comment by ddworken** [comment]
Can you try running `hishtory update` to get the latest version? Looking through the code for `makeTableColumns`, I believe this has already been fixed. And I can't reproduce it with bash, zsh, or fish.

**Comment by adRn-s** [comment]
Indeed, it was version 0.193... updated to 0.199 now :) Thanks!
