### ISSUE TITLE
Add config option to exclude commands with non-zero exit codes

### ISSUE THREAD

**Issue by d4v3y0rk** [ddworken/hishtory#76]
I don't know about other people but I often mistype a command and end up having to run it again. It would be nice to have the opt-in ability to not store commands with non-zero exit codes.

**Comment by ddworken** [comment]
Interesting! I think this is a reasonable FR. Though for the record, this is already somewhat possible by just search for `exit_code:0` to filter to entries with an exit code of `0`.

**Comment by ddworken** [comment]
I realized I implemented this, but forgot to document it or respond here, so my apologies for that! This is now documented in the README under the "default search filters" section. Please let me know if you run into any issues with this.
