### ISSUE TITLE
.bashrc settings no longer work

### ISSUE THREAD

**Issue by lbassett-lba** [ddworken/hishtory#79]
I had some configuration in my .bashrc file, for formating the prompt, displaying certain information, etc. These settings were invaluable to me. Sadly, after installing hishtory, these settings no longer apply and I am faced with a plain-formatted bash prompt. The settings are still in .barshrc. They just do not matter anymore.

**Comment by ddworken** [comment]
Ah interesting! What OS are you on? And how are you opening a terminal (what app? is it via SSH?). If you run `source ~/.bashrc` does it fix the issue? 

If so, I believe that adding these lines to `~/.bash_profile` should fix your issue:

```
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi
```

Please let me know, and if this fixes it I'll figure out how to include this by default in the installer.

**Comment by lbassett-lba** [comment]
Thank you so much for replying quickly.

`source ~/.bashrc ` fixed it. I have no idea what sorcery is at play, but I'm grateful for it. Hishtory seems like a fantastic tool and I've no doubt it's going to become an indispensible part of my life. Thank you!

**Comment by lbassett-lba** [comment]
Sorry, I should add, for the benefit of anyone else reading this with the same problem:

I also had to add the lines you recommended to `~/.bash_profile`. This appears to have fixed it.
