### ISSUE TITLE
delete entry with Ctrl-K shows error when using offline mode

### ISSUE THREAD

**Issue by LaurentBxl** [ddworken/hishtory#80]
Hi,

When I press Ctrl-K in the query table to delete an entry, I get this error:

An unrecoverable error occured: failed to send deletion request to backend service, this may cause commands to not get deleted on other instances of hishtory: failed to POST /api/v1/add-deletion-request: status_code=502

I'm using hishtory offline

Thanks

**Comment by ddworken** [comment]
Fixed, thank you for catching this!
