### ISSUE TITLE
Ctrl-R shell history allows navigation to command but then selects the wrong command

### ISSUE THREAD

**Issue by cowboygneox** [ddworken/hishtory#82]
It's odd, when I select a line down the list, it more often than not selects the wrong command as the output.

Reproduction:

1. Ctrl-R
2. Search for something
3. Go to the 4th line
4. It chooses the 3rd line, or at least not the 4th.
 
**Config:**
```
% hishtory -v
hiSHtory version v0.206

% hishtory config-get custom-columns

% hishtory config-get enable-control-r
true

% hishtory config-get displayed-columns
Timestamp Command 

% hishtory config-get filter-duplicate-commands
true
```

**Comment by cowboygneox** [comment]
This looks to be an issue with `filter-duplicate-commands`. It doesn't seem to consider that as part of its indexing.

**Comment by cowboygneox** [comment]
Confirmed: `filter-duplicate-commands = false` is the current work around.

**Comment by michaldanaj** [comment]
I confirm. Thanks for work around.
