### ISSUE TITLE
Change directory

### ISSUE THREAD

**Issue by Janhouse** [ddworken/hishtory#83]
Not sure if this would be possible but it would be great if there was also a shortcut (in the ctlr+r menu)  that would also change the directory to the one the command was executed from before. And then after changing the directory, provide the command.

**Comment by ddworken** [comment]
This is now supported via `ctrl+x`. I wanted this to be `ctrl+enter` or `shift+enter`, but sadly terminal emulators don't support modifiers for the enter key, so that isn't possible. Run `hishtory update` to get the latest version that supports this. :)

**Comment by Janhouse** [comment]
Great! Would be amazing if it would not put that `cd` command in the history afterwards of using ctlr+x but I can live with it. :slightly_smiling_face:

**Comment by ajuitar** [comment]
Wouldn't it be better to to have the change directory command to be followed by " && " instead of " ; "? At least I manually replace the semi-colon with && out of the fear that the change of directory would fail for some reason and the main command would run is a wrong directory.

**Comment by ddworken** [comment]
Good point! I updated this to change it to `&&` and have released that change. If you run `hishtory update`, you should get the latest version with this tweak.
