### ISSUE TITLE
Synchronizing between remote and local computer

### ISSUE THREAD

**Issue by jcdegiorgi** [ddworken/hishtory#88]
Hi,

Nice job! I like this software.
Thanks.

I have noticed the following problem on my VM Ubuntu 22.04 (master) and my computer LinuxMint 20.1.
I did as explained on your [main page](https://github.com/ddworken/hishtory), part `Then to install hishtory on your other computers...` .
From my Ubuntu (master), launch the following command:
$ hishtory query

It takes ages (more than 10 minutes) to give the result.
Would it comes from the DB size?
```
mint201:~/.hishtory$ tree -ash
.
├── [1.5K]  config.sh
├── [1.1K]  config.zsh
├── [ 47M]  hishtory
├── [1024K]  hishtory-2023-05-18T12-17-59.197.log
├── [1024K]  hishtory-2023-05-18T12-18-09.465.log
├── [1023K]  hishtory-2023-05-18T12-18-16.886.log
├── [1023K]  hishtory-2023-05-18T12-18-25.078.log
├── [1024K]  hishtory-2023-05-18T12-24-21.748.log
├── [1024K]  hishtory-2023-05-18T12-24-37.146.log
├── [1024K]  hishtory-2023-05-18T12-24-53.182.log
├── [1024K]  hishtory-2023-05-18T12-25-01.161.log
├── [1024K]  hishtory-2023-05-18T12-25-25.930.log
├── [1024K]  hishtory-2023-05-18T12-25-37.246.log
├── [ 514]  .hishtory.config
├── [8.3M]  .hishtory.db
├── [ 32K]  .hishtory.db-shm
├── [8.7M]  .hishtory.db-wal
└── [736K]  hishtory.log
```

and sometimes the following error appears:
`2023/05/18 14:40:01 hishtory v0.207 fatal error at github.com/ddworken/hishtory/client/cmd/query.go:87: DB error: database is locked (5) (SQLITE_BUSY)`
Why the DB is locked?

Thanks,
Jean-Claude

**Comment by ddworken** [comment]
If you run `hishtory update`, you'll get the latest version of hishtory which has both better performance (all queries now run async to minimize latency) and better handling of DB locking errors (which are caused by poor DB performance). If you're still running into either of these issues, please reopen this and let me know!
