### ISSUE TITLE
bash completions not working?

### ISSUE THREAD

**Issue by vnnegt** [ddworken/hishtory#89]
i have `hiSHtory` installed on an ubuntu machine

per the `hishtory completion bash --help` instructions i ran the command `source <(hishtory completion bash)`

but completions aren't working after running the command

i also added the completions to a bash script, manually sourced the bash script and completions still didn't work

bash-completion is installed:
```
bash-completion/bionic,now 1:2.8-1ubuntu1 all [installed]
```

thanks

**Comment by vnnegt** [comment]
is this a known issue? just trying to determine if it's my distro or not thanks

**Comment by ddworken** [comment]
My apologies for the silence here! This seems to be some issue with the dependency that we use for command line parsing (github.com/spf13/cobra). I haven't gotten the chance to look into this yet, but I will do my best to figure this out and keep this issue updated.

**Comment by ddworken** [comment]
Hmm, so I'm honestly not too sure what is going on here. This issue reproduced last week, but with the latest version of hishtory it seems to reliably work (tested on bash+zsh on MacOS and Linux). Can you trying running `hishtory update` and seeing whether that fixes the issue for you?

**Comment by vnnegt** [comment]
> Hmm, so I'm honestly not too sure what is going on here. This issue reproduced last week, but with the latest version of hishtory it seems to reliably work (tested on bash+zsh on MacOS and Linux). Can you trying running `hishtory update` and seeing whether that fixes the issue for you?

yup, it works now!

thanks, love this tool!

**Comment by ddworken** [comment]
Thank you! I'm glad it is working now, so I'll mark this as closed. If you or anyone else notices any issues with this, please re-open this issue.
