### ISSUE TITLE
Glitches with different terminal sizes

### ISSUE THREAD

**Issue by Janhouse** [ddworken/hishtory#9]
I noticed that with my default 120x27 terminal size hishtory doesn't draw correctly. Resizing the terminal doesn't redraw the UI either. And having a larger terminal before opening hishtory draws the UI smaller, not using the full terminal size. I guess it doesn't yet support custom size and dynamic resizing?

As a bonus bug - typing in a term that has no results and pressing Ctrl + r triggers an exception.

See the attached video:

[Screencast from 2022-11-02 14-54-32.webm](https://user-images.githubusercontent.com/1036439/199495157-7dea02a9-11ee-47bb-9637-4a22c43c7278.webm)

**Comment by ddworken** [comment]
Ah, thank you for this! Fixed with 6983b04c4708b837eb4e22705915e09deb87baf9 and 085d2a917f370c36d7ac4d7b8add51a69040b93a. If you run `hishtory update` you should get the latest version that handles terminal resizing. And if you run into any other issues please re-open this!
