### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by danielbair** [ddworken/hishtory#94]
hishtory fatal error at github.com/ddworken/hishtory/hishtory.go:372: failed to check if command was hidden: failed to replace config file with the updated version: rename ~/.hishtory/.hishtory.config.tmp ~/.hishtory/.hishtory.config: no such file or directory

**Comment by ddworken** [comment]
This is due to a race condition that was fixed in b7533479a3d0483facbce7115b0b2bc0aac0d77b. If you run `hishtory update` you'll get an updated version of hishtory that has fixed this bug.
