### ISSUE TITLE
Webiste in redirect loop

### ISSUE THREAD

**Issue by Roxedus** [ddworken/hishtory#95]
I figure I can grab the binaries manually, but I would also like to see what the install script does. I cannot find it in the source code, in any  logical branch.

**Comment by andyvalerio** [comment]
Same issue here.

**Comment by jakezp** [comment]
Still happening here too

**Comment by papanito** [comment]
`install.py` can be found at [`backend/web/landing/www/install.py`](https://github.com/ddworken/hishtory/blob/master/backend/web/landing/www/install.py)

**Comment by ddworken** [comment]
My apologies for this! I've fixed the error and set up monitoring to ensure that I get alerted if this ever happens again.
