### ISSUE TITLE
User for a column?

### ISSUE THREAD

**Issue by fawqsir** [ddworken/hishtory#97]
Just wanted to say thanks. This is increditble! What are the columns that have already been defined?
Is there a column for the user that ran a command?

ie: `hishtory config-set displayed-columns Command Timestamp CWD Runtime "Exit Code" LocalUsername Hostname`

result:
2023/08/08 11:06:00 hishtory v0.208 fatal error at github.com/ddworken/hishtory/client/cmd/query.go:46:failed to build row for entry=data.HistoryEntry{LocalUsername:"<REDACTED>", Hostname:"<REDACTED>", Command:"hishtory config-set displayed-columns Command Timestamp CWD Runtime \"Exit Code\" LocalUsername Hostname", CurrentWorkingDirectory:"~/", HomeDirectory:"/home/<REDACTED>", ExitCode:0, StartTime:time.Date(2023, time.August, 8, 11, 5, 59, 0, time.Local), EndTime:time.Date(2023, time.August, 8, 11, 5, 59, 812310136, time.Local), DeviceId

`hishtory config-set displayed-columns Command Timestamp CWD Runtime "Exit Code" User Hostname`

result:
12023/08/08 11:13:35 hishtory v0.208 fatal error at github.com/ddworken/hishtory/client/cmd/query.go:46:failed to build row for entry=data.HistoryEntry{LocalUsername:"<REDACTED>", Hostname:"<REDACTED>", Command:"hishtory config-set displayed-columns Command Timestamp CWD Runtime \"Exit Code\" User Hostname", CurrentWorkingDirectory:"~/", HomeDirectory:"/home/<REDACTED>", ExitCode:0, StartTime:time.Date(2023, time.August, 8, 11, 13, 31, 0, time.Local), EndTime:time.Date(2023, time.August, 8, 11, 13, 31, 893769404, time.Local), DeviceId

**Comment by ddworken** [comment]
Thanks for the issue! With 66f3dc13ec4c55d45aa659707ad62e9aeb4590df, this is now supported via `hishtory config-add displayed-columns User`.
