### ISSUE TITLE
Selecting and pressing enter on an entry from hishtory does not do anything

### ISSUE THREAD

**Issue by hcandraw** [ddworken/hishtory#98]
Thanks for the awesome product.

There seems to be a problem with my hishtory install.  I'm not sure what.  

I'm on a Mac.  When I do CMD+R, select an entry, and press enter, nothing is happening and instead, hishtory quit and I'm back to my terminal.

I'm not sure what else to add since there wasn't any error during the installation and when executing the hishtory command.

**Comment by ddworken** [comment]
Interesting. What OS version, shell, and shell version are you using? I personally am using hishtory on my mac (with both bash and zsh), so it does generally work.

**Comment by ddworken** [comment]
If you can reproduce this on the latest version of hishtory, please let me know and reopen this issue!

**Comment by nwithan8** [comment]
Same issue, same OS.
